# create fluxcdtutorial namespace
apiVersion: v1
kind: Namespace
metadata:
  name: fluxcdtutorial
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ngxapp
  namespace: fluxcdtutorial
spec:
  interval: 30s
  path: ./deploy
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: ngxapp
  timeout: 3m0s
  wait: true
