---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysecret
  namespace: fluxcdtutorial
spec:
  encryptedData:
    password: AgAOFWTTFBqTwQe8ZWhSmnXYz9M7yU0oICTD+J3HQIB5n1nFlKfTdEUolTe/40Y6NLS0Ztz7XcopQP+4N4dvITHm13TLcfVPeiyKZYzr1bij0ADpIBHrwv4P4yfX8XabxaXn6SvA7QYbVgLegcjCnMss9q09/0t8NqhzsGQImhqShq9o93b9jfNeGSYn7JrHMhGLuZtLNkx0gNGyUfktqSodOU+rzHffxkzrftrX756MY/PJXLipGPkoFIKIhXKZwly3BRVbCNAtoWQTBprjqRZjYQbtGOMuYvjlGUQKSlxh1SwYPwXtwLTSV+TwjzZZiZEHKhGxD6Crr7LePZenwUvyc30/p+Gg5cdUBMqgMGJoiGtVCyBJJRqaRXxh1biFni6e/9owI3wZl75HpUgLWXkNK+WzrRcz7Y8q8OSWE9//htOrJt6arZ7YVs6fTvWdmZVAB3S8OF3EMG7ApK2TiXXHMDroEm36dnb1DPKNt/TbdRo26hC9bsTiBlX1elwy3RWcGVIJDSSDrNzRtL+xIJo0NXmrI4Z15XCOkYoIvaSBCtU0wQDE05dlzRIrlEnRp+rMXMlMDhQq1px8ekIz0cnnRkX5JA0RhXQogMa8/Bjo7X3ESv3S8J/qWz/Up1T6mK20fAgZjxMXiUPQEE52+xMgBFSqEMtWzQW7FCn0Es7nkxdHhkXwgr0tEBdz6ufmSiQJkIZmF2EkGA==
    username: AgAYOPvUN/2sAHniKhh18pb7ih0x7YvIcr38f680vGPs1IuL8VZxGxu5b+jJ/5PUv8p6bYSTYH9+p+tA+/7CDtZSanAqGmi2Cq72oIB2BkLbaE3pRGp+AolN4Pn10SN4veA/Bx6p0HnBibjTb49gXZ9Lzu58zRERhWZP52twz8sJAwGZetJOkVFpzhWvjC54U0Gdx2pXQbdZFGh4iTRRqwt/IoxbjNV7aqXZZ0AQAGmvRF0JL2rCeVV9dIISGIYqjJcF8I2Gij48c6jOCobcrORRj+Q3vTLuQJ28ujbXAjbydWdxA5H5aSNoA1y/tYnqxFYZ5PRpbYqDnqeUnR3iQ72FmPTJkGWgp6mjLZJLAXe/s4+g9Y+9EYaqfpF3JoUoQvHbHNiAN37niFR/T8cB9VZ2Tu/edAvOdDLDpNmbfkRDzVpTGSy+bx5/2HC3Lr2ErKnflqr3DpUAa7Uz7SrAqjJhAmv47NebEG4uepeWfE02Wrw+q6QQ8ktmsT2jfxTD7wkuis77bu1IhwYVQ/2vQ+7ID7ryiZ4EAo8dggSHoJlXyor+LvBkNJ4kT8wClGD45IftSevlQB2HaGlvNFKzdp1WQv5K+8MHjJx7qwNcsJRd5P2J5xFZ61+YAC+KTI+nuEjAztbK5VIQyOAmZV4gFuOLbxdS0RQlWSfFt+lAoFMTCulWEemlmE3qopanlU1HbmFXmhiP5A==
  template:
    metadata:
      name: mysecret
      namespace: fluxcdtutorial
    type: Opaque
