---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mysecret
  namespace: fluxcdtutorial
spec:
  encryptedData:
    password: AgCdH2Nh7fwqIgPqVtbq1/3hIsQ/Bt8rRp2i24ix+87+kPrnRXEF1+NweelOwU+b6mbUn7w2Owjfz5r81pIpZ6SCuLjlGSNpX3tEx3E+w3Xt8vCkLxLagQ3cowlc82PlxsvaPNJFGrNqC0XNuzb8b5YsrnSK0Z1hOqi9E2jtaqNdzM+IVHb0pEkJvT7HEd1slyUonhxH7AIeywqSPuLMuQzoLxX75uGJqxwDsgZx7rEOPMHQyk09xvEE7ocueXKtiaZLqLRj/rnJfvX8TgkYRDDtdi4XvslxYLpcqZ55mDTj+PSDfEauJHdKP7j/UUC3TYtOte9cPZEI0398u+AUcRrBgSyOOxe1cxdJm+C8gJBwmthAWzMk9VK50FFWrGzeNSZ1ffyFNXtBYDSl4FAX2J65OtckAdrUkGEQoPW8+HJRFoseSwxmZuybbpqMnXV2qzSsA+YzESe8RM18dyaNZoU7bZQy0h060AhaIsuykGK4pt8JVfpLsLC07/V6qIzdkm4EuKDpzu+HTX+AUvR2WjZhLsN0SoQ1c9j6/JG+5/JzRfpWYxEY0evfx8+wStZCbmPjZJqU7JEfXZM/iL4xTz0evkHMSNGnsait3UWoRKee7n7OEegOgi+9Ivwl1EnRokm5Ix6MFgtHtNGtwUEjpzSNJyMfKp8zLvCDFhziQzVpoD9deRr/nQopNzLxm3abcymifd2pvnIofA==
    username: AgDJPsf7qOkNqdbjsC5LrdlBjLdodsnOPGAxx2HkkX0Yq/zCBZRjk1taxUNLp4dxEr0Al7yCMDniil0qJSOipNJ0x5MepKND0O197Pr7Q/ZTJ095i6sXi/Gtkpw9PjFMu2ta6oqPZABmTGoGnQcdSUmsOoW2ZpvvS6aDECd0KVnviayuKlReAwDVo6e//na1VR29BJM2cj+D+VKCYcuDieiBJXK6YAv9d8ll1qPIIdlG71BF8my8cRjy92Ci3+ugUycCfZmaZ6k9oCRNcnNdATMqDf0UAX0ME0F68g7P5epNcttJKmJlmigZ0q1wdOtF4/nKI0hT3wa2AR0+DMfznkNOMbYMS7eiNoEras09+pQzquVxffk5dqbppLbxXqIn+Vn5bgA9HMnxpWE+F20MWSd1fqTfTi1AZAwrxzgOEegCxtIZO9LhkPb9bZJUIt+PzvHCCXTnc6zL0HPGolQa1Yh46xLGwqdhVhSaaisVDJb4ynYmJkMI4HzQG9KVrfcoj4xe+08Wz9mF9MyuhQy7JBeWE8igDJuch5RT3Dcr6YBlDdkclTZoULoTWYD6ztfbWHbaMhjTZ946l4J7k6AOCZtdt7TKySdgM0v7zYapr7wsHECl93SJDuWbISzcIHa4yPpmBOFtMtUY15XzwGf1nfsArwuFQb2jbCRB8LmSRx5z3973VLFUHwkOTVzCvveqaiWP5l6uwA==
  template:
    metadata:
      name: mysecret
      namespace: fluxcdtutorial
    type: Opaque
